// Signin
// KQL used to get sign-in from user and get some details from IdentityInfo Table

let Time_Range = 1d;
let Result_Filter = ""; // "", "success", "failure" or an specificaly ResultType 50126
let Target_UPN = "";
let User_Info =
    IdentityInfo
    | where AccountUPN contains Target_UPN
    | extend Account_lower = tolower(AccountUPN)
    | summarize arg_max(TimeGenerated, *) by Account_lower;
SigninLogs
| where TimeGenerated > ago(Time_Range)
| where UserPrincipalName contains Target_UPN
| where isempty(Result_Filter) or (Result_Filter =~ "success" and ResultType == 0) or (Result_Filter =~ "failure" and ResultType != 0) or (Result_Filter !in~ ("success", "failure") and tostring(ResultType) == Result_Filter)
| extend UPN_lower = tolower(UserPrincipalName)
| extend Result_Auth_Status = iff(ResultType != 0, strcat_delim(" , ", ResultType, ResultSignature, ResultDescription), "Success")
| extend Device_Name = tostring(DeviceDetail.displayName), Device_OS = tostring(DeviceDetail.operatingSystem), Device_ID = tostring(DeviceDetail.deviceId), Device_Managed = tostring(DeviceDetail.trustType)
| extend Device_Properties = iff(Device_Name != "", strcat_delim(" , ", strcat("Host: ", Device_Name), Device_Managed, strcat("OS: ", Device_OS), strcat("ID: ", Device_ID)), strcat("OS: ", Device_OS, " || N/A"))
| extend MFA = tostring(MfaDetail.authMethod)
| extend MFA_Status = iff(AuthenticationRequirement != "singleFactorAuthentication", strcat_delim(" , ", AuthenticationRequirement, MFA), "singleFactorAuthentication")
| mv-apply Policy_Item = ConditionalAccessPolicies on ( where tostring(Policy_Item.result) in~ ("success", "failure") | summarize CA_Policy = strcat_array(make_list(strcat(tostring(Policy_Item.displayName), " == ", tostring(Policy_Item.result))), " ||| ")) | extend CA_Policy = iff(isempty(CA_Policy), "N/A", CA_Policy)
| extend ASN_IP_Address = strcat_delim(", ", strcat("ASN: ", AutonomousSystemNumber), strcat("IP: ", IPAddress))
| join kind=leftouter (User_Info) on $left.UPN_lower == $right.Account_lower
| order by TimeGenerated desc
| project TimeGenerated, UserPrincipalName, UserType, ASN_IP_Address, SessionId, CorrelationId, Location, Device_Properties, Result_Auth_Status, MFA_Status, ConditionalAccessStatus, CA_Policy, AppDisplayName, ResourceDisplayName, ClientAppUsed, UserAgent, JobTitle, Department, IsAccountEnabled, RiskLevelAggregated, RiskLevelDuringSignIn, RiskState, RiskEventTypes