// USER NON-INTERACTIVE SIGN-INS
// RESULT FILTER:
// "" = all | "success" = ResultType 0 | "failure" = ResultType != 0 | "50126" = código específico
let Time_Range = 1d;
let Target_UPN = "";
let Result_Filter = "";
let User_Info =
    IdentityInfo
    | where AccountUPN contains Target_UPN
    | extend Account_lower=tolower(AccountUPN)
    | summarize arg_max(TimeGenerated, *) by Account_lower;
AADNonInteractiveUserSignInLogs
| where TimeGenerated > ago(Time_Range)
| where UserPrincipalName contains Target_UPN
| where isempty(Result_Filter) or (Result_Filter =~ "success" and tostring(ResultType) == "0") or (Result_Filter =~ "failure" and tostring(ResultType) != "0") or (Result_Filter !in~ ("success", "failure") and tostring(ResultType) == Result_Filter)
| extend UPN_lower=tolower(UserPrincipalName), DeviceDetail_Dynamic=todynamic(DeviceDetail), MfaDetail_Dynamic=todynamic(MfaDetail), ConditionalAccessPolicies_Dynamic=todynamic(ConditionalAccessPolicies)
| extend Result_Auth_Status=iff(tostring(ResultType) != "0", strcat_delim(" , ", ResultType, ResultSignature, ResultDescription), "Success")
| extend Device_Name=tostring(DeviceDetail_Dynamic.displayName), Device_OS=tostring(DeviceDetail_Dynamic.operatingSystem), Device_ID=tostring(DeviceDetail_Dynamic.deviceId), Device_Managed=tostring(DeviceDetail_Dynamic.isManaged), Device_Compliant=tostring(DeviceDetail_Dynamic.isCompliant), Device_Trust_Type=tostring(DeviceDetail_Dynamic.trustType)
| extend Device_Properties=iff(isnotempty(Device_Name), strcat_delim(" , ", strcat("Host: ", Device_Name), strcat("Managed: ", Device_Managed), strcat("Compliant: ", Device_Compliant), strcat("Trust: ", Device_Trust_Type), strcat("OS: ", Device_OS), strcat("ID: ", Device_ID)), strcat("OS: ", Device_OS, " || N/A"))
| extend MFA=tostring(MfaDetail_Dynamic.authMethod)
| extend MFA_Status=iff(AuthenticationRequirement != "singleFactorAuthentication", strcat_delim(" , ", AuthenticationRequirement, MFA), "singleFactorAuthentication")
| mv-apply Policy_Item=ConditionalAccessPolicies_Dynamic on ( where tostring(Policy_Item.result) in~ ("success", "failure") | summarize CA_Policy=strcat_array(make_list(strcat(tostring(Policy_Item.displayName), " == ", tostring(Policy_Item.result))), " ||| ") | extend CA_Policy=iff(isempty(CA_Policy), "N/A", CA_Policy))
| extend ASN_IP_Address=strcat_delim(", ", strcat("ASN: ", AutonomousSystemNumber), strcat("IP: ", IPAddress))
| extend Token_Properties=strcat_delim(", ", strcat("Issuer: ", TokenIssuerType), strcat("TokenType: ", IncomingTokenType))
| join kind=leftouter (User_Info) on $left.UPN_lower == $right.Account_lower
| project TimeGenerated, UserPrincipalName, UserType, Token_Properties, SessionId, CorrelationId, UniqueTokenIdentifier, ASN_IP_Address, Location, Device_Properties, Result_Auth_Status, MFA_Status, ConditionalAccessStatus, CA_Policy, AppDisplayName, ResourceDisplayName, ClientAppUsed, UserAgent, JobTitle, Department, IsAccountEnabled, RiskLevelAggregated, RiskLevelDuringSignIn, RiskState, RiskEventTypes
| order by TimeGenerated desc